package com.dcmc.apps.taskmanager.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WorkGroupUserRoleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkGroupUserRoleAllPropertiesEquals(WorkGroupUserRole expected, WorkGroupUserRole actual) {
        assertWorkGroupUserRoleAutoGeneratedPropertiesEquals(expected, actual);
        assertWorkGroupUserRoleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkGroupUserRoleAllUpdatablePropertiesEquals(WorkGroupUserRole expected, WorkGroupUserRole actual) {
        assertWorkGroupUserRoleUpdatableFieldsEquals(expected, actual);
        assertWorkGroupUserRoleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkGroupUserRoleAutoGeneratedPropertiesEquals(WorkGroupUserRole expected, WorkGroupUserRole actual) {
        assertThat(actual)
            .as("Verify WorkGroupUserRole auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkGroupUserRoleUpdatableFieldsEquals(WorkGroupUserRole expected, WorkGroupUserRole actual) {
        assertThat(actual)
            .as("Verify WorkGroupUserRole relevant properties")
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkGroupUserRoleUpdatableRelationshipsEquals(WorkGroupUserRole expected, WorkGroupUserRole actual) {
        assertThat(actual)
            .as("Verify WorkGroupUserRole relationships")
            .satisfies(a -> assertThat(a.getGroup()).as("check group").isEqualTo(expected.getGroup()));
    }
}
